name: Clean old data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete data older than 24 hours
        run: |
          DAY_AGO=$(($(date +%s%3N) - 24*60*60*1000))
          curl -X DELETE "https://audiozvonok-b340d-default-rtdb.firebaseio.com/ads.json?orderBy=\"timestamp\"&endAt=$DAY_AGO"
          curl -X DELETE "https://audiozvonok-b340d-default-rtdb.firebaseio.com/messages.json?orderBy=\"timestamp\"&endAt=$DAY_AGO"
          curl -X DELETE "https://audiozvonok-b340d-default-rtdb.firebaseio.com/calls.json?orderBy=\"timestamp\"&endAt=$DAY_AGO"
          curl -X DELETE "https://audiozvonok-b340d-default-rtdb.firebaseio.com/call_messages.json?orderBy=\"timestamp\"&endAt=$DAY_AGO"
          curl -X DELETE "https://audiozvonok-b340d-default-rtdb.firebaseio.com/status.json?orderBy=\"timestamp\"&endAt=$DAY_AGO"
